export default {
  H500: {
    fontSize: { base: '32px', md: '52px' },
    fontWeight: 'bold',
    lineHeight: '120%',
    letterSpacing: '0.02em',
    // fontFeatureSetting: { base: 'liga 0' },
  },
  H400: {
    fontSize: { base: '28px', md: '38px' },
    fontWeight: 'bold',
    lineHeight: { base: '122%', md: '126%' },
    letterSpacing: '0.01em',
    // fontFeatureSetting: { base: 'liga 0' },
  },
  H300: {
    fontSize: { base: '26px', md: '28px' },
    fontWeight: 'bold',
    lineHeight: { base: '122%', md: '128%' },
    letterSpacing: '0.01em',
    // fontFeatureSetting: { base: 'liga 0' },
  },
  H200: {
    fontSize: { base: '22px' },
    fontWeight: 'bold',
    lineHeight: { base: '128%' },
    letterSpacing: '0.01em',
    // fontFeatureSetting: { base: 'liga 0' },
  },
  H100: {
    fontSize: { base: '17px', md: '18px' },
    fontWeight: 'bold',
    lineHeight: { base: '140%', md: '136%' },
    letterSpacing: '0.01em',
    // fontFeatureSetting: { base: 'liga 0' },
  },
  'headline-page': {
    // you can also use responsive styles
    fontFamily: 'Bangers, cursive',
    fontWeight: 'normal',
    lineHeight: 'tall',
    letterSpacing: 'wide',
    fontSize: ['5xl', '7xl'],
  },
  headline: {
    fontWeight: 'bold',
    lineHeight: 'tall',
    letterSpacing: 'normal',
    fontSize: ['3xl', '5xl'],
  },
  'headline-accent': {
    fontFamily: 'Bangers, cursive',
    fontWeight: 'bold',
    lineHeight: ['normal', 'tall'],
    letterSpacing: 'normal',
    fontSize: ['3xl'],
  },
  'headline-intersitial': {
    fontWeight: 'bold',
    lineHeight: 'taller',
    letterSpacing: 'normal',
    fontSize: ['3xl'],
  },
  'headline-card': {
    fontWeight: 'bold',
    lineHeight: 'normal',
    letterSpacing: 'normal',
    fontSize: ['md'],
  },
  'jam-content-body': {
    'h1, h2': {
      margin: '0px auto 20px',
      fontFamily: 'Bangers, cursive',
      fontWeight: 'bold',
      lineHeight: 'tall',
      letterSpacing: 'normal',
      fontSize: ['3xl'],
      width: '55%',
    },
    'h3, h4, h5': {
      margin: '0px auto 20px',
      fontFamily: 'Bangers, cursive',
      fontWeight: 'bold',
      lineHeight: 'tall',
      letterSpacing: 'normal',
      fontSize: ['xl'],
      width: '55%',
    },
    p: {
      margin: '10px auto',
      width: '55%',
    },
    'pre.prisma-code': {
      margin: '0px 0px 0px auto',
    },
    ul: {
      listStyle: 'none',
      padding: 0,
      margin: '10px auto',
      width: '55%',
    },
    img: {
      width: '100%',
      marginLeft: 'auto',
      marginRight: 'auto',
    },
  },
};
