name: Deploy Studio
on:
  push:
    branches: [master, development]
jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: studio
    steps:
      - name: Set the path value
        run: |
          echo 'studio/' >> $GITHUB_PATH
      - uses: actions/setup-node@v2-beta
        with:
          node-version: '12'
      - uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
      - name: Install dependencies
        run: |
          yarn
      - name: Deploy Sanity
        run: |
          set -e
          # Put your environment variables here. Don't forget
          # to create secrets for them on GitHub:
          # https://docs.github.com/en/actions/configuring-and-managing-workflows/creating-and-storing-encrypted-secrets
          # Make sure to add a secret for SANITY_AUTH_TOKEN
          SANITY_AUTH_TOKEN="${{ secrets.SANITY_AUTH_TOKEN }}" SANITY_STUDIO_PREVIEW_SECRET="{{ secrets.SANITY_STUDIO_PREVIEW_SECRET }}" deploy
          SANITY_AUTH_TOKEN="${{ secrets.SANITY_AUTH_TOKEN }}" yarn deploy:gql --playground
