name: Deploy Studio
# Deployment is handled on Vercel. Studio is treated as a separate project.
# This is only to deploy the Graphql Endpoint to staging. Production (currently)
# to be done manually.
on:
  push:
    branches: [development]
jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: studio
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2-beta
        with:
          node-version: '12'
      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - uses: actions/cache@v2
        id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: Install All dependencies
        run: |
          yarn install
      - name: Deploy Sanity
        env:
          AUTH_TOKEN: ${{ secrets.SANITY_AUTH_TOKEN }}
          PREVIEW_SECRET: ${{ secrets.SANITY_STUDIO_PREVIEW_SECRET }}
        run: |
          set -e
          # Put your environment variables here. Don't forget
          # to create secrets for them on GitHub:
          # https://docs.github.com/en/actions/configuring-and-managing-workflows/creating-and-storing-encrypted-secrets
          # Make sure to add a secret for SANITY_AUTH_TOKEN
          SANITY_AUTH_TOKEN="$AUTH_TOKEN" yarn deploy:gql --playground --dataset staging
